src/Entity/Soutenance.php
<?php

namespace App\Entity;

use App\Repository\SoutenanceRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=SoutenanceRepository::class)
 */
class Soutenance
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity=Enseignant::class, inversedBy="soutenances")
     */
    private $numjury;

    /**
     * @ORM\OneToMany(targetEntity=Etudiant::class, mappedBy="soutenance")
     */
    private $numetudiant;

    /**
     * @ORM\Column(type="date")
     */
    private $date_soutenance;

    /**
     * @ORM\Column(type="float")
     */
    private $note;

    public function __construct()
    {
        $this->numetudiant = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNumjury(): ?Enseignant
    {
        return $this->numjury;
    }

    public function setNumjury(?Enseignant $numjury): self
    {
        $this->numjury = $numjury;

        return $this;
    }

    /**
     * @return Collection<int, Etudiant>
     */
    public function getNumetudiant(): Collection
    {
        return $this->numetudiant;
    }

    public function addNumetudiant(Etudiant $numetudiant): self
    {
        if (!$this->numetudiant->contains($numetudiant)) {
            $this->numetudiant[] = $numetudiant;
            $numetudiant->setSoutenance($this);
        }

        return $this;
    }

    public function removeNumetudiant(Etudiant $numetudiant): self
    {
        if ($this->numetudiant->removeElement($numetudiant)) {
            // set the owning side to null (unless already changed)
            if ($numetudiant->getSoutenance() === $this) {
                $numetudiant->setSoutenance(null);
            }
        }

        return $this;
    }

    public function getDateSoutenance(): ?\DateTimeInterface
    {
        return $this->date_soutenance;
    }

    public function setDateSoutenance(\DateTimeInterface $date_soutenance): self
    {
        $this->date_soutenance = $date_soutenance;

        return $this;
    }

    public function getNote(): ?float
    {
        return $this->note;
    }

    public function setNote(float $note): self
    {
        $this->note = $note;

        return $this;
    }
}

src/Form/SoutenanceType.php
<?php

namespace App\Form;

use App\Entity\Enseignant;
use App\Entity\Soutenance;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;

class SoutenanceType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('date_soutenance')
            ->add('note',null,['attr' => ['maxlength' => 2,'max'=>20,'min'=>0]])
            ->add('numJury',EntityType::class,array('class'=>Enseignant::class,'choice_label'=>'prenom','choice_value'=>'id'))

        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Soutenance::class,
        ]);
    }
}

src/Controller/SoutenanceController.php
<?php

namespace App\Controller;

use App\Entity\Soutenance;
use App\Form\SoutenanceType;
use App\Repository\SoutenanceRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/soutenance")
 */
class SoutenanceController extends AbstractController
{
    /**
     * @Route("/", name="app_soutenance_index", methods={"GET"})
     */
    public function index(SoutenanceRepository $soutenanceRepository): Response
    {
        return $this->render('soutenance/index.html.twig', [
            'soutenances' => $soutenanceRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="app_soutenance_new", methods={"GET", "POST"})
     */
    public function new(Request $request, SoutenanceRepository $soutenanceRepository): Response
    {
        $soutenance = new Soutenance();
        $form = $this->createForm(SoutenanceType::class, $soutenance);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $soutenanceRepository->add($soutenance);
            return $this->redirectToRoute('app_soutenance_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('soutenance/new.html.twig', [
            'soutenance' => $soutenance,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="app_soutenance_show", methods={"GET"})
     */
    public function show(Soutenance $soutenance): Response
    {
        return $this->render('soutenance/show.html.twig', [
            'soutenance' => $soutenance,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="app_soutenance_edit", methods={"GET", "POST"})
     */
    public function edit(Request $request, Soutenance $soutenance, SoutenanceRepository $soutenanceRepository): Response
    {
        $form = $this->createForm(SoutenanceType::class, $soutenance);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $soutenanceRepository->add($soutenance);
            return $this->redirectToRoute('app_soutenance_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('soutenance/edit.html.twig', [
            'soutenance' => $soutenance,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="app_soutenance_delete", methods={"POST"})
     */
    public function delete(Request $request, Soutenance $soutenance, SoutenanceRepository $soutenanceRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$soutenance->getId(), $request->request->get('_token'))) {
            $soutenanceRepository->remove($soutenance);
        }

        return $this->redirectToRoute('app_soutenance_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/soutenance/_delete_form.html.twig
<form method="post" action="{{ path('app_soutenance_delete', {'id': soutenance.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ soutenance.id) }}">
    <button class="btn btn-danger">Delete</button>
</form>

templates/soutenance/_form.html.twig
{{ form_start(form) }}


{{form_label(form.note,null,{
    'label': 'Note',
    'label_attr': {'class': 'g'}})}}
    {{ form_widget(form.note,{'attr':{'class':'form-control inputDefault w-50','placeholder':'Veuillez entrer la note','required':'true'}}) }}


{{form_label(form.date_soutenance,null,{
    'label': 'Date',
    'label_attr': {'class': 'g'}})}}
    {{ form_widget(form.date_soutenance,{'attr':{'class':'date-picker','required':'true'}}) }}


{{form_label(form.numJury,null,{
    'label': 'Jury',
    'label_attr': {'class': 'g'}})}}
    {{ form_widget(form.numJury,{'attr':{'class':'form-select','required':'true'}}) }}

 <button class="btn btn-success">{{ button_label|default('Enregistrer') }}</button>

{{ form_end(form) }}

templates/soutenance/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Soutenance{% endblock %}

{% block body %}
{% include('./navbar/index.html.twig') %}
    <h1>Edit Soutenance</h1>

    {{ include('soutenance/_form.html.twig', {'button_label': 'Update'}) }}

    <a class="btn btn-warning" href="{{ path('app_soutenance_index') }}">back to list</a>

    {{ include('soutenance/_delete_form.html.twig') }}
{% endblock %}

templates/soutenance/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Soutenance index{% endblock %}

{% block body %}
{% include('./navbar/index.html.twig') %}
    <h1>Soutenance index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Date_soutenance</th>
                <th>Note</th>
                <th>NomJury</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for soutenance in soutenances %}
            <tr>
                <td>{{ soutenance.id }}</td>
                <td>{{ soutenance.dateSoutenance ? soutenance.dateSoutenance|date('Y-m-d') : '' }}</td>
                <td>{{ soutenance.note }}</td>
                <td>
                <a href="/enseignant/{{soutenance.numjury.id}}"  style="color:blue"> 

                {{soutenance.numjury.nom}}
                </a>
                <td>
                    <a  class="btn btn-info" href="{{ path('app_soutenance_show', {'id': soutenance.id}) }}">show</a>
                    <a  class="btn btn-warning" href="{{ path('app_soutenance_edit', {'id': soutenance.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="4">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a   class="btn btn-success" href="{{ path('app_soutenance_new') }}">Create new</a>
{% endblock %}

templates/soutenance/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Soutenance{% endblock %}

{% block body %}
{% include('./navbar/index.html.twig') %}
    <h1>Create new Soutenance</h1>

    {{ include('soutenance/_form.html.twig') }}

    <a class="btn btn-danger" href="{{ path('app_soutenance_index') }}">back to list</a>
{% endblock %}

templates/soutenance/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Soutenance{% endblock %}

{% block body %}
{% include('./navbar/index.html.twig') %}
    <h1>Soutenance</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ soutenance.id }}</td>
            </tr>
            <tr>
                <th>Date_soutenance</th>
                <td>{{ soutenance.dateSoutenance ? soutenance.dateSoutenance|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Note</th>
                <td>{{ soutenance.note }}</td>
            </tr>
               <tr>
                <th>NomJury</th>
                <td>
                <a href="/enseignant/{{soutenance.numjury.id}}" style="color:blue">

                {{ soutenance.numjury.nom }}
                </a>
                </td>
            </tr>
        </tbody>
    </table>

    <a class="btn btn-warning" href="{{ path('app_soutenance_index') }}">back to list</a>

    <a class="btn btn-info" href="{{ path('app_soutenance_edit', {'id': soutenance.id}) }}">edit</a>

    {{ include('soutenance/_delete_form.html.twig') }}
{% endblock %}